### PR TITLE
Replace deprecated API

### PR DESCRIPTION
**Pull request by gloomy-ghost**

### CODE REVIEW

**Comment by Aminadav** [comment]
Thank's. Have you tested it?
There is any change to the behavior? 
Is this just refactoring or are you fixing an issue?

**Comment by gloomy-ghost** [comment]
I haven't test it yet, but it shouldn't be any behavior changes since it's just minor refactoring 😃

**Comment by Aminadav** [comment]
Please test it. let me know if you need any help :)

**Comment by gloomy-ghost** [comment]
Tested and good to go

**Comment by Aminadav** [comment]
great. will be merged

**Pull request merged**
